config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {omniauth_callbacks: "oauth_callbacks"}

  root to: "questions#index"

  concern :voteable do
    member do
      patch :like
      patch :dislike
      patch :revote
    end
  end

  concern :commentable do
    member { patch :add_comment }
  end

  resources :questions, only: %i[index show new create update destroy], concerns: [:voteable, :commentable] do
    resources :answers, only: %i[create update destroy], concerns: [:voteable, :commentable] do
      member do
        patch :best
      end
    end
  end

  resources :files, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resource :profiles do
        collection do
          get :me
          get :others
        end
      end

      resources :questions, except: %i[new edit], shallow: true do
        resources :answers, except: %i[new edit]
      end
    end
  end

  mount ActionCable.server => "/cable"
end

app/models/question.rb
class Question < ApplicationRecord
  include Voteable
  include Commentable

  has_many :answers, -> { sort_by_best }, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  belongs_to :author, class_name: "User", foreign_key: "author_id"

  has_many_attached :files

  accepts_nested_attributes_for :links, :reward, reject_if: :all_blank, allow_destroy: true

  scope :last_day_created, -> { where("created_at > ?", 24.hours.ago).order(created_at: :asc) }

  validates :title, :body, :author, presence: true
end

app/controllers/api/v1/questions_controller.rb
module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      def index
        @questions = Question.all

        render json: @questions, each_serializer: QuestionSerializer
      end

      def show
        @question = find_question
        render json: @question, serializer: QuestionSerializer
      end

      def create
        authorize Question

        @question = Question.new(question_params.merge(author: current_user))

        if @question.save
          render json: @question, serializer: QuestionSerializer
        else
          render json: {errors: @question.errors.full_messages}, status: :unprocessable_entity
        end
      end

      def update
        @question = find_question

        authorize @question

        if @question.update(question_params)
          render json: @question, serializer: QuestionSerializer
        else
          render json: {errors: @question.errors.full_messages}, status: :unprocessable_entity
        end
      end

      def destroy
        @question = find_question

        authorize @question

        if @question.destroy
          head :no_content
        else
          render json: {errors: @question.errors.full_messages}, status: :unprocessable_entity
        end
      end

      private

      def find_question
        Question.find(params[:id])
      end

      def question_params
        params.require(:question).permit(:title, :body)
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: [:index, :show]

  after_action :publish_question, only: [:create]

  def index
    @questions = Question.all
    authorize @questions
  end

  def show
    @question = find_question
    authorize @question
    @answers = @question.answers.sort_by_best
    @answer = Answer.new
    @answer.links.new

    gon.push({
      question_id: @question.id,
      sid: session&.id&.public_id
    })
  end

  def new
    @question = Question.new
    authorize @question
    @question.links.build
    @reward = Reward.new(question: @question)
  end

  def create
    @question = Question.new(question_params)
    authorize @question
    @question.author = current_user

    if @question.save
      redirect_to @question, notice: "Your question successfully created."
    else
      render :new
    end
  end

  def update
    @question = find_question
    authorize @question
    @question.update(question_params)
  end

  def destroy
    @question = find_question
    authorize @question
    @question.destroy
    redirect_to root_path, notice: "Your question successfully deleted."
  end

  private

  def find_question
    Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
      links_attributes: [:id, :name, :url, :_destroy],
      reward_attributes: [:title, :image])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast("questions_channel", {
      question: {
        title: @question.title,
        url: url_for(@question)
      }
    })
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= render "shared/errors", resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body

  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  .question-links
    = f.fields_for :links do |link|
    .links
      = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

  p Reward
  = f.fields_for :reward do |r|
    .create-reward
      p
        = r.label :title, "Reward title"
        = r.text_field :title
      p
        = r.label :image, "Image"
        = r.file_field :image, direct_upload: true

  p= f.submit "Ask"

app/views/questions/_question.html.slim
div.question
  = render 'shared/vote', voteable: @question

  .question-error

  .question-title
    h1 = @question.title

  .question-body
    p = @question.body

  - if @question.reward.present?
    h3 Reward:
    = image_tag url_for(@question.reward.image), size: "36"
    = @question.reward.title

  - if @question.files.attached?
    - @question.files.each do |file|
      p.attachment id="file-#{file.id}"
        = link_to file.filename.to_s, url_for(file)
        -if policy(file.record).destroy?
          = link_to "Delete file", file_path(file), method: :delete, remote: true

  -if policy(@question).update?
    .question-control
      p= link_to "Edit question", '#', class: 'edit-question-link', data: { question_id: @question.id }
      p= link_to "Delete question", question_path(@question), method: :delete

      = form_with model: @question,
        class: 'hidden',
        local: false,
        html: { id: "edit-question-#{@question.id}"} do |f|

        p
          = f.label :title
          = f.text_field :title
        p
          = f.label :body
          = f.text_area :body
        p
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true
        p= f.submit "Save"

        p
        #links
          = f.fields_for :links do |link|
            =render "links/link_fields", f: link
          .links
            = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'


  .question-links
    - if @question.links.present?
      = render "shared/links", resource: @question, action: nil

  = render "shared/comments", resource: @question

app/views/questions/index.html.slim
- if policy(Question).create?
  p = link_to "Ask question", new_question_path

.questions
  - @questions.each do |question|
    p= link_to question.title, question

app/views/questions/new.html.slim
= render "form"

app/views/questions/show.html.slim
h1 Question:

.question-container
  = render @question

.answers
  = render @question.answers, action: :show

.question-answer
  = render "answers/form"

app/views/questions/update.js.erb
$('.question-error').html('<%= render "shared/errors", resource: @question %>');

<% if !@question.errors.present? %>
  $(".question-container").html('<%= j render @question %>');
<% end %>