config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {omniauth_callbacks: "oauth_callbacks"}

  root to: "questions#index"

  concern :voteable do
    member do
      patch :like
      patch :dislike
      patch :revote
    end
  end

  concern :commentable do
    member { patch :add_comment }
  end

  resources :questions, only: %i[index show new create update destroy], concerns: [:voteable, :commentable] do
    resources :answers, only: %i[create update destroy], concerns: [:voteable, :commentable] do
      member do
        patch :best
      end
    end
  end

  resources :files, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resource :profiles do
        collection do
          get :me
          get :others
        end
      end

      resources :questions, except: %i[new edit], shallow: true do
        resources :answers, except: %i[new edit]
      end
    end
  end

  mount ActionCable.server => "/cable"
end

app/views/shared/_comments.html.slim
.comments
  - if resource.comments.present?
    .mb-3
      .fw-bold Comments:
      - resource.comments.each do |c|
        .comment
          div.comment-author.mb-1
            'Comment by #{c.author.email}
          div.comment-body.mb-1
            = c.body

-if current_user.present?
  = form_with url: custom_polymorphic_comment_path(resource),
    method: :patch,
    local: false,
    class: "add_comment",
    data: { type: 'json' } do |f|

    div.comment_errors
      = render "shared/errors", resource: resource

    div.mb-3
      = f.label :body, "Type your comment", class: "form-label"
      = f.text_area :body, rows: 1, class: "comment-body"

      = f.submit "Comment", class: "btn btn-primary"

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_iframe.html.slim
- iframe_url = "data:text/html;charset=utf-8,<head><base target='_blank' /></head><body><script src=#{link}.js></script></body>"
- if action == :create
  iframe.gist-content src="#{iframe_url}" width="100%" height="100%"
- else
  iframe.gist-content data-gist-url="#{iframe_url}" width="100%" height="100%"

app/views/shared/_links.html.slim
p Links:
ul
  - resource.links.each do |link|
    -if link.match_gist?
      li= link_to link.name, link.url
      = render "shared/iframe", link: link.url, action: action
    -else
      li= link_to link.name, link.url

app/views/shared/_nav.html.slim
nav.navbar.navbar-light.bg-light
  .container
    = link_to "QNA", root_path, class: 'navbar-brand'
    navbar-text
      - if user_signed_in?
        = current_user.email
        = link_to "Log out", destroy_user_session_path, method: :delete
        = link_to "My rewards", rewards_path
      - else
        = link_to 'Log in', new_user_session_path
        = link_to "Registration", new_user_registration_path

app/views/shared/_vote.html.slim
- if current_user.present?
  div.votes
    div.mb-3
      = link_to custom_polymorphic_vote_path(voteable, action: :like),
        method: :patch,
        class: 'btn btn-outline-success like me-2',
        remote: true,
        data: { type: 'json' } do
          i.bi.bi-hand-thumbs-up

      span.votes-sum.me-2.fs-5(class="#{'text-success' if voteable.votes_sum > 0} #{'text-danger' if voteable.votes_sum < 0}")
        = voteable.votes_sum

      = link_to custom_polymorphic_vote_path(voteable, action: :dislike),
        method: :patch,
        class: 'btn btn-outline-danger dislike me-2',
        remote: true,
        data: { type: 'json' } do
          i.bi.bi-hand-thumbs-down

      - classes = 'btn btn-outline-primary revote me-2'
      - classes += ' hidden' if !voteable.voted?(current_user)

      = link_to "Revote", custom_polymorphic_vote_path(voteable, action: :revote),
        method: :patch,
        class: classes,
        remote: true,
        data: { type: 'json' }