config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {omniauth_callbacks: "oauth_callbacks"}

  root to: "questions#index"

  concern :voteable do
    member do
      patch :like
      patch :dislike
      patch :revote
    end
  end

  concern :commentable do
    member { patch :add_comment }
  end

  resources :questions, only: %i[index show new create update destroy], concerns: [:voteable, :commentable] do
    resources :answers, only: %i[create update destroy], concerns: [:voteable, :commentable] do
      member do
        patch :best
      end
    end
  end

  resources :files, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resource :profiles do
        collection do
          get :me
          get :others
        end
      end

      resources :questions, except: %i[new edit], shallow: true do
        resources :answers, except: %i[new edit]
      end
    end
  end

  mount ActionCable.server => "/cable"
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Voteable
  include Commentable

  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  belongs_to :question
  belongs_to :author, class_name: "User", foreign_key: "author_id"

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, :author, presence: true

  scope :sort_by_best, -> { order(best: :desc) }

  def set_the_best
    Answer.transaction do
      Answer.where(question_id: question_id, best: true).update_all(best: false)
      update(best: true)
      update!(reward: question.reward) if question.reward
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: :show
  helper_method :current_question

  after_action :publish_answer, only: [:create]

  def create
    @answer = current_question.answers.create(answer_params.merge(author: current_user))
    authorize @answer
    @answer.save
  end

  def update
    @answer = find_answer
    authorize @answer
    @answer.update(answer_params)
  end

  def destroy
    @answer = find_answer
    authorize @answer
    @answer.destroy
  end

  def best
    @answer = find_answer
    authorize @answer
    @answer.set_the_best
  end

  private

  def current_question
    @current_question ||= Question.with_attached_files.find(params[:question_id])
  end

  def find_answer
    current_question.answers.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [],
      links_attributes: [:id, :name, :url, :_destroy])
  end

  def publish_answer # метод отвечает за передачу данных в канал answers_channel
    return if @answer.errors.any?
    ActionCable.server.broadcast("answers_channel_#{current_question.id}", broadcast_attributes)
  end

  def broadcast_attributes
    votes = {
      sum: @answer.votes_sum,
      like_url: helpers.custom_polymorphic_vote_path(@answer, action: :like),
      dislike_url: helpers.custom_polymorphic_vote_path(@answer, action: :dislike)
    }

    files = @answer.files.map { |file| {filename: file.filename.to_s, url: url_for(file)} }
    links = @answer.links.map { |link| {name: link.name, url: link.url} }

    {
      answer: @answer.attributes.merge(votes: votes, files: files, links: links),
      sid: session.id.public_id
    }
  end
end

app/controllers/api/v1/answers_controller.rb
module Api
  module V1
    class AnswersController < Api::V1::BaseController
      def index
        @answers = find_question_answers

        render json: @answers, each_serializer: AnswerSerializer
      end

      def show
        find_answer

        render json: @answer, serializer: AnswerSerializer
      end

      def create
        authorize Answer

        @answer = find_question_answers.new(answer_params.merge(author: current_user))

        return render_answer if @answer.save

        render_errors
      end

      def update
        find_answer

        authorize @answer

        return render_answer if @answer.update(answer_params)

        render_errors
      end

      def destroy
        find_answer

        authorize @answer

        return head :no_content if @answer.destroy

        render_errors
      end

      private

      def find_answer
        @answer ||= Answer.find(params[:id])
      end

      def find_question_answers
        Question.find(params[:question_id]).answers
      end

      def answer_params
        params.require(:answer).permit(:body)
      end

      def render_answer
        render json: @answer, serializer: AnswerSerializer
      end

      def render_errors
        render json: {errors: @answer.errors.full_messages}, status: :unprocessable_entity
      end
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div.answer id="answer_#{answer.id}"

  -if answer.best
    .best-answer
      h3= "The best answer to the question:"
      p= answer.body
  -else
    p= answer.body

  = render 'shared/vote', voteable: answer

  .answer-links
    - if answer.links.present?
      = render "shared/links", resource: answer, action: action

  p
    -if answer.files.attached?
      - answer.files.each do |file|
        p.attachment id="file-#{file.id}"
          = link_to file.filename.to_s, url_for(file)
          -if policy(file.record).destroy?
            = link_to "Delete file", file_path(file), method: :delete, remote: true

  -if policy(answer).update?
    li= link_to "Delete answer", question_answer_path(answer.question, answer), remote: true, method: :delete
    li= link_to "Edit", "#", class: "edit-answer-link", data: { answer_id: answer.id }

  -if policy(answer).best? && !answer.best
    li= link_to "The Best Answer", best_question_answer_path(answer.question ,answer), remote: true, method: :patch

  div class=["answer-error-#{answer.id}"]

  .answer-edit
    = form_with model: [answer.question, answer], class: 'hidden', html: {id: "edit-answer-#{answer.id}" }, local: false do |f|
      p
        = f.label :body, "Your answer"
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true

      p
      #links
        = f.fields_for :links do |link|
          =render "links/link_fields", f: link
        .links
          = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'
      p= f.submit "Save"

  = render "shared/comments", resource: answer

app/views/answers/_form.html.slim
.answer-errors
  = render "shared/errors", resource: @answer

= form_with model: [@question, @answer], class: 'new-answer', local: false do |f|
  p
    = f.label :body
    = f.text_area :body

  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  .new-answer-links
    = f.fields_for :links do |link|
    .links
      = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

  p= f.submit "Answer"

app/views/answers/best.js.erb
$('.answers').html('<%= j render current_question.answers, action: nil %>');

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render "shared/errors", resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer, action: :create %>');
  $('.new-answer #answer_body').val('');
  $('.new-answer-links .nested-fields').remove();
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  $('#answer_<%= @answer.id %>').remove();
<% end %>

app/views/answers/update.js.erb
$('.answers .answer-error-<%= @answer.id %>').html('<%= render "shared/errors", resource: @answer %>');

<% if !@answer.errors.present? %>
  $('#answer_<%= @answer.id %>').replaceWith('<%= j render @answer, action: :update %>');
<% end %>